name: Release

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  clear-code-cells:
    name: Clear code cells
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Clear code cells
        run: python .github/clear_code_cells.py
        env:
          DRY_RUN: false
      - name: Remove unfinished lessons
        run: python .github/remove_unfinished_lessons.py
        env:
          DRY_RUN: false
      - uses: actions/upload-artifact@v4
        with:
          name: Chem 18 contents ${{ github.sha }}
          path: |
            L10n/
            Lesson */
            requirement.txt
            README.md
            Setup Instruction.md

  create-release:
    name: Create release
    needs: clear-code-cells
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          name: Chem 18 contents ${{ github.sha }}
      - run: zip -r 'Chem 18 (${{ github.ref_name }}).zip' ./*
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Chem 18 (${{ github.ref_name }}).zip
